FROM python:3.10

# Installiere benötigte Pakete für OpenCV & Tesseract OCR
RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    tesseract-ocr-deu \
    libtesseract-dev \
    libasound2-dev \
    libavcodec-extra \
    libavformat-dev \
    libswscale-dev \
    libxext6 \
    libxrender-dev \
    libsm6 \
    ffmpeg \
    git-lfs \
    && rm -rf /var/lib/apt/lists/*

RUN pip install poetry